apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
secretGenerator:
  - name: hape-aws-credentials
    files:
      - credentials=.aws-credentials
generatorOptions:
  disableNameSuffixHash: true
