apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hape-edc-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: hape-edc-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
