{
 "title": "EKS Deployment Cost",
 "tags": [
  "eks",
  "cost",
  "hape"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Exporter Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hape_eks_deployment_cost_exporter_up"
    }
   ]
  },
  {
   "title": "Total Hourly Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hape_eks_deployment_cost_total_usd{period=\"hourly\"}"
    }
   ]
  },
  {
   "title": "Total Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hape_eks_deployment_cost_total_usd{period=\"monthly\"}"
    }
   ]
  },
  {
   "title": "Total Yearly Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hape_eks_deployment_cost_total_usd{period=\"yearly\"}"
    }
   ]
  },
  {
   "title": "Top 10 Workloads By Hourly Cost",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10, hape_eks_deployment_cost_workload_max_hourly_usd)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  }
 ]
}